version: '3.3'
services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  web:
    image: shilsny/foodgram
    restart: always
    volumes:
      - media_value:/app/media/
  nginx:
    image: nginx:1.19.3
    depends_on: 
      - web 
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media_value:/var/html/media/
volumes: 
  media_value: