# Generated by Django 2.2.16 on 2022-08-24 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0004_auto_20220823_1234"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingCartRecipe",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.Recipe",
                        verbose_name="Рецепт",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_cart_recipes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рецепт из списка покупок",
                "verbose_name_plural": "Рецепты из списка покупок",
            },
        ),
        migrations.AddConstraint(
            model_name="shoppingcartrecipe",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="unique_shopping_cart_item"
            ),
        ),
    ]
