# Generated by Django 2.2.16 on 2022-08-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20220821_1654"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscription",
            name="unique_subscribe",
        ),
    ]
