# Generated by Django 2.2.16 on 2022-08-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20220821_1705"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("subscribed_to", "subscriber"), name="unique_subscribe"
            ),
        ),
    ]
