# Generated by Django 2.2.16 on 2022-08-21 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20220821_1759"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"verbose_name": "Подписка", "verbose_name_plural": "Подписки"},
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscribed_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriber",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписан на",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscriber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscribed_to",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписчик",
            ),
        ),
    ]
